# scheduler-audit-analyzer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-audit-analyzer
  namespace: kube-system
  labels:
    app: scheduler-audit-analyzer
    component: scheduler-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-audit-analyzer
  template:
    metadata:
      labels:
        app: scheduler-audit-analyzer
        component: scheduler-tools
    spec:
      serviceAccountName: scheduler-tools
      containers:
      - name: scheduler-audit-analyzer
        image: scheduler-tools/scheduler-audit-analyzer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: METRICS_PORT
          value: "8081"
        - name: HTTP_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: audit-logs
          mountPath: /var/log/audit
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: scheduler-audit-analyzer-config
      - name: audit-logs
        hostPath:
          path: /var/log/audit
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-audit-analyzer
  namespace: kube-system
  labels:
    app: scheduler-audit-analyzer
    component: scheduler-tools
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: scheduler-audit-analyzer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-audit-analyzer-config
  namespace: kube-system
  labels:
    app: scheduler-audit-analyzer
    component: scheduler-tools
data:
  config.yaml: |
    log_level: info
    metrics_port: 8081
    health_port: 8080
    timeout: 30s
    audit:
      log_path: "/var/log/audit"
      watch_interval: 10s
      max_file_size: "100MB"
      retention_days: 7
    security:
      enable_anomaly_detection: true
      alert_threshold: 0.8
      suspicious_patterns:
        - "failed_scheduling"
        - "unauthorized_access"
        - "privilege_escalation"