# scheduler-analyzer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-analyzer
  namespace: kube-system
  labels:
    app: scheduler-analyzer
    component: scheduler-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-analyzer
  template:
    metadata:
      labels:
        app: scheduler-analyzer
        component: scheduler-tools
    spec:
      serviceAccountName: scheduler-tools
      containers:
      - name: scheduler-analyzer
        image: scheduler-tools/scheduler-analyzer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: METRICS_PORT
          value: "8081"
        - name: HTTP_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: scheduler-analyzer-config
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-analyzer
  namespace: kube-system
  labels:
    app: scheduler-analyzer
    component: scheduler-tools
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: scheduler-analyzer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-analyzer-config
  namespace: kube-system
  labels:
    app: scheduler-analyzer
    component: scheduler-tools
data:
  config.yaml: |
    log_level: info
    metrics_port: 8081
    health_port: 8080
    timeout: 30s
    analysis:
      interval: 60s
      history_retention: 24h
      enable_deep_analysis: true
      performance_thresholds:
        latency_p95: 5s
        failure_rate: 0.05
        queue_length: 100
    scheduler:
      name: default-scheduler
      namespace: kube-system