# 调度器健康检查配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-health-config
  namespace: kube-system
  labels:
    app: kube-scheduler
    component: health-check
data:
  health-checks.json: |
    {
      "checks": [
        {
          "name": "api-server",
          "url": "https://kubernetes.default.svc.cluster.local/healthz",
          "interval": "30s",
          "timeout": "10s",
          "retries": 3,
          "expectedCode": 200
        },
        {
          "name": "scheduler-metrics",
          "url": "http://localhost:10251/metrics",
          "interval": "60s",
          "timeout": "5s",
          "retries": 2,
          "expectedCode": 200
        },
        {
          "name": "scheduler-healthz",
          "url": "http://localhost:10251/healthz",
          "interval": "30s",
          "timeout": "5s",
          "retries": 2,
          "expectedCode": 200
        },
        {
          "name": "leader-election",
          "url": "http://localhost:10251/healthz/leaderelection",
          "interval": "60s",
          "timeout": "10s",
          "retries": 3,
          "expectedCode": 200
        }
      ],
      "alerting": {
        "webhookUrl": "http://alertmanager.monitoring.svc.cluster.local:9093/api/v1/alerts",
        "enabled": true,
        "cooldown": "300s"
      }
    }
  
  alert-rules.yaml: |
    groups:
    - name: scheduler.health
      rules:
      - alert: SchedulerAPIServerUnhealthy
        expr: scheduler_health_check{check="api-server"} == 0
        for: 2m
        labels:
          severity: critical
          component: scheduler
        annotations:
          summary: "Scheduler cannot reach API server"
          description: "The scheduler has been unable to reach the API server for {{ $value }} minutes."
      
      - alert: SchedulerMetricsUnhealthy
        expr: scheduler_health_check{check="scheduler-metrics"} == 0
        for: 5m
        labels:
          severity: warning
          component: scheduler
        annotations:
          summary: "Scheduler metrics endpoint unhealthy"
          description: "The scheduler metrics endpoint has been unhealthy for {{ $value }} minutes."
      
      - alert: SchedulerLeaderElectionFailed
        expr: scheduler_health_check{check="leader-election"} == 0
        for: 3m
        labels:
          severity: critical
          component: scheduler
        annotations:
          summary: "Scheduler leader election failed"
          description: "The scheduler leader election has been failing for {{ $value }} minutes."
      
      - alert: SchedulerHealthCheckHigh
        expr: scheduler_health_check_latency_seconds > 5
        for: 2m
        labels:
          severity: warning
          component: scheduler
        annotations:
          summary: "Scheduler health check latency high"
          description: "Scheduler health check latency is {{ $value }}s, which is above the 5s threshold."

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-health-service
  namespace: kube-system
  labels:
    app: kube-scheduler
    component: health-check
spec:
  selector:
    app: kube-scheduler
  ports:
  - name: health
    port: 10251
    targetPort: 10251
    protocol: TCP
  - name: metrics
    port: 10259
    targetPort: 10259
    protocol: TCP
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scheduler-health-monitor
  namespace: kube-system
  labels:
    app: kube-scheduler
    component: health-check
spec:
  selector:
    matchLabels:
      app: kube-scheduler
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  - port: health
    interval: 30s
    path: /healthz
    scheme: http