# workload-scheduling-policies.yaml
# Web前端工作负载调度策略
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-frontend-scheduling-policy
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: web-frontend-scheduler
      plugins:
        filter:
          enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
          - name: PodTopologySpread
        score:
          enabled:
          - name: NodeResourcesFit
            weight: 3
          - name: PodTopologySpread
            weight: 5
          - name: NodeAffinity
            weight: 2
      pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            type: LeastAllocated  # 保证资源充足
      - name: PodTopologySpread
        args:
          defaultConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
    percentageOfNodesToScore: 30  # 快速调度
    parallelism: 8
---
# 批处理工作负载调度策略
apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-processing-scheduling-policy
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: batch-processing-scheduler
      plugins:
        filter:
          enabled:
          - name: NodeResourcesFit
          - name: TaintToleration
        score:
          enabled:
          - name: NodeResourcesFit
            weight: 1
      pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            type: MostAllocated  # 提高资源利用率
    percentageOfNodesToScore: 100  # 全节点评分
    parallelism: 16