# YAML 基础练习题
# 请修正以下 YAML 文件中的错误，并完成练习题

# ==========================================
# 练习 1: 修正语法错误
# ==========================================

# 以下 YAML 包含多个语法错误，请找出并修正：

# 错误示例 (请修正):
apiVersion: v1
kind: Pod
metadata:
  name: practice-pod
  labels:              # 错误：缩进不正确
    app: myapp         # 错误：冒号后缺少空格
    version: v1.0      # 错误：缩进过多
spec:
  containers:
  - name: web          # 错误：列表项缺少适当缩进
    image: nginx:1.21
    ports:
    - containerPort: 80
      protocol: TCP

# ==========================================
# 练习 2: 完成配置
# ==========================================

# 请完成以下 Kubernetes Service 配置：
apiVersion: v1
kind: Service
metadata:
  name: practice-service
  # TODO: 添加标签 app: practice
  
spec:
  # TODO: 设置服务类型为 ClusterIP
  
  # TODO: 添加选择器，选择 app: practice 的 Pod
  
  # TODO: 添加端口配置
  # - 名称: http
  # - 端口: 80
  # - 目标端口: 8080
  # - 协议: TCP
  

# ==========================================
# 练习 3: 创建复杂结构
# ==========================================

# 请创建一个 Deployment 配置，要求：
# - 名称: practice-deployment
# - 副本数: 3
# - 标签: app: practice, tier: frontend
# - 容器名称: web
# - 镜像: nginx:1.21
# - 容器端口: 8080
# - 环境变量: ENV=production, DEBUG=false
# - 资源限制: CPU 500m, 内存 256Mi
# - 资源请求: CPU 250m, 内存 128Mi

# 在此处编写您的 Deployment 配置:


# ==========================================
# 练习 4: 数据类型练习
# ==========================================

# 请创建一个包含以下数据的 YAML 结构：

# 个人信息:
person:
  # TODO: 姓名 (字符串): 张三
  
  # TODO: 年龄 (数字): 28
  
  # TODO: 是否已婚 (布尔值): true
  
  # TODO: 配偶 (空值): null
  
  # TODO: 爱好 (列表): 阅读, 游泳, 编程
  
  # TODO: 联系方式 (嵌套字典):
  # - 邮箱: zhangsan@example.com
  # - 电话: +86-13800138000
  # - 地址:
  #   - 城市: 北京
  #   - 邮编: 100000
  
  # TODO: 工作经历 (列表，每项包含字典):
  # - 公司: ABC科技
  #   职位: 软件工程师
  #   年份: 2020-2022
  # - 公司: XYZ公司
  #   职位: 高级工程师
  #   年份: 2022-至今
  

# ==========================================
# 练习 5: 多行字符串
# ==========================================

# 请使用适当的多行字符串语法完成以下配置：

config:
  # TODO: 使用 | 语法创建保留换行符的多行字符串
  # 内容为:
  # 第一行配置
  # 第二行配置
  # 第三行配置
  server_config: 
  
  # TODO: 使用 > 语法创建折叠换行符的多行字符串
  # 内容为:
  # 这是一个很长的描述文本，
  # 它会被折叠成一行，
  # 所有换行符都会变成空格。
  description: 

# ==========================================
# 练习 6: 高级特性
# ==========================================

# 请使用锚点和引用完成以下配置：

# TODO: 定义一个锚点 &common-labels，包含:
# app: practice
# version: v1.0
# environment: production


# TODO: 创建两个 Pod 配置，都使用上面定义的公共标签
# Pod 1: practice-pod-1，额外标签 component: frontend
# Pod 2: practice-pod-2，额外标签 component: backend


# ==========================================
# 练习答案检查
# ==========================================

# 完成练习后，可以使用以下命令验证您的 YAML 语法：
# 
# 1. Python 验证:
#    python3 -c "import yaml; yaml.safe_load(open('practice-exercises.yml'))"
# 
# 2. kubectl 验证 (仅适用于 Kubernetes 资源):
#    kubectl apply --dry-run=client -f practice-exercises.yml
# 
# 3. yamllint 检查 (如果已安装):
#    yamllint practice-exercises.yml
# 
# 4. 使用演示脚本验证:
#    ./yaml-demo.sh --validate

# ==========================================
# 提示和技巧
# ==========================================

# 1. 缩进规则:
#    - 使用 2 个空格缩进
#    - 不要使用 Tab 键
#    - 同一层级保持相同缩进

# 2. 冒号规则:
#    - 冒号后必须有空格
#    - 键名不能包含冒号

# 3. 列表规则:
#    - 使用 - 表示列表项
#    - - 后面要有空格
#    - 列表项要正确缩进

# 4. 引号使用:
#    - 简单字符串可以不用引号
#    - 包含特殊字符时使用引号
#    - 数字字符串需要引号

# 5. 注释:
#    - 使用 # 添加注释
#    - 注释可以单独一行或行尾

# ==========================================
# 扩展练习
# ==========================================

# 如果您已经完成了上述练习，可以尝试以下扩展练习：

# 1. 创建一个完整的微服务应用配置，包括：
#    - Namespace
#    - Deployment
#    - Service
#    - ConfigMap
#    - Secret (注意不要包含真实密码)

# 2. 使用 YAML 文档分隔符 (---) 在一个文件中定义多个资源

# 3. 练习使用不同的数据类型：
#    - 字符串、数字、布尔值
#    - 列表和字典的嵌套
#    - 多行字符串的不同格式

# 4. 研究 Kubernetes 的其他资源类型：
#    - Ingress
#    - PersistentVolume
#    - StatefulSet
#    - DaemonSet

# 祝您学习愉快！